---
# tasks file for wordpress
- name: Download wordpress file
  ansible.builtin.unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/
    remote_src: yes

- name: Set ownership of WordPress files
  file:
    path: /var/www/wordpress
    owner: www-data
    group: www-data
    mode: "755"
    recurse: yes

- name: Add wp-config.php
  template:
    src: ../templates/wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: "644"

# Create site config for ansible.rabinmishra.com.np
- name: Add ansible site to nginx
  template:
    src: ../templates/default.j2
    dest: /etc/nginx/sites-available/ansible.rabinmishra.com.np
    owner: root
    group: root
    mode: "0644"
  become: yes

- name: Enable ansible site
  file:
    src: /etc/nginx/sites-available/ansible.rabinmishra.com.np
    dest: /etc/nginx/sites-enabled/ansible.rabinmishra.com.np
    state: link
  become: yes

# Create site config for wordpress.rabinmishra.com.np
- name: Add wordpress site to nginx
  template:
    src: ../templates/wordpress.j2
    dest: /etc/nginx/sites-available/wordpress.rabinmishra.com.np
    owner: root
    group: root
    mode: "0644"
  become: yes

- name: Enable wordpress site
  file:
    src: /etc/nginx/sites-available/wordpress.rabinmishra.com.np
    dest: /etc/nginx/sites-enabled/wordpress.rabinmishra.com.np
    state: link
  become: yes

# Remove default nginx site to avoid conflicts
- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes
