---
# tasks file for pma
- name: Install phpmyadmin
  apt:
    name: phpmyadmin
    state: latest

- name: Configure phpmyadmin
  ansible.builtin.template:
    src: ../templates/pma.j2
    dest: /etc/nginx/sites-available/pma.rabinmishra.com.np
    owner: root
    group: root
    mode: "0644"

- name: Enable pma site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/pma.rabinmishra.com.np
    dest: /etc/nginx/sites-enabled/pma.rabinmishra.com.np
    state: link
  become: yes
