---
# tasks file for certbot

- name: Install certbot nginx python3
  apt:
    name:
      - python3-certbot-nginx
    state: latest

# Test nginx configuration before running certbot
- name: Test nginx configuration
  ansible.builtin.command: nginx -t
  register: nginx_test
  failed_when: nginx_test.rc != 0

- name: Reload nginx to apply new configurations
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Generate SSL certificate with Nginx integration
  ansible.builtin.command: >-
    certbot --nginx             
    --non-interactive           
    --agree-tos                 
    --email mishrarabin92@gmail.com 
    --redirect                  
    --staple-ocsp               
    -d {{ item }}
  loop: "{{ my_domains }}"
  register: certbot_result
  changed_when: >-
    'Successfully received certificate.' in certbot_result.stdout or
    'Certificate not yet due for renewal; still operating' not in certbot_result.stdout
  notify: restart nginx
